### ISSUE TITLE
custom validation section needs more info

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/activerecord-validations-lab#7]
definitely was at a lost on where to begin for the custom validation. It would've been helpful to mention using regex, or errors.add, any thing like that to guide in the right thinking to problem solve. Additionally, how we would we test if the validations were working? we would have to create the view templates?

**Comment by darrendaz** [comment]
Wouldn't have guessed the solution for the custom validation. Documentation searched and read so far doesn't contain details on this usage either oof.

**Comment by sgharms** [comment]
@BrittanyTinnin 

We updated the documentation to give a hint in be48b7e based on your suggestion. We're going to do a bigger pass on this entire topic in end 2019, but wanted to address this issue now.

Validations can be tested by using custom Rails extensions to RSpec. Here's a good guide: https://til.hashrocket.com/posts/af87b1eaa8-test-validation-errors-with-rspec

@darrendaz Your concern should be addressed by the change as well.
