### ISSUE TITLE
Missing Gemfile.lock causes bundle failure

### ISSUE THREAD

**Issue by AspenJames** [learn-co-curriculum/activerecord-validations-lab#8]
See same issue here: https://github.com/learn-co-curriculum/model-class-methods-lab/issues/41

**Comment by heavenlyboheme** [comment]
Gemfile.lock is created after running "bundle install" in the terminal. 
![screen shot 2019-01-15 at 4 55 49 pm](https://user-images.githubusercontent.com/16994388/51215414-7bcba880-18e6-11e9-9cce-8c24e8d3fe66.png)

**Comment by AspenJames** [comment]
See [clarification of the issue](https://github.com/learn-co-curriculum/model-class-methods-lab/issues/41#issuecomment-454594185)

**Comment by sgharms** [comment]
@AspenJames Can you confirm whether this issue was fixed in 8d9105302?

**Comment by AspenJames** [comment]
Looks fine
